version: '3'
services:
  register:
    build: ./register
    ports:
      - "3001:3001"
    environment:
      DB_HOST: 172.17.0.1
      DB_USER: user
      DB_PASSWORD: senha123
      DB_NAME: usersdb

  login:
    build: ./login
    ports:
      - "3002:3002"
    environment:
      DB_HOST: 172.17.0.1
      DB_USER: user
      DB_PASSWORD: senha123
      DB_NAME: usersdb

  profile:
    build: ./profile
    ports:
      - "3003:3003"
    environment:
      DB_HOST: 172.17.0.1
      DB_USER: user
      DB_PASSWORD: senha123
      DB_NAME: usersdb